### ISSUE TITLE
Found a mistake here that breaks our Pipeline

### ISSUE THREAD

**Issue by savigny030** [medikoo/memoizee#139] opened 2024-05-24 08:08 UTC
https://github.com/medikoo/memoizee/blob/6aa37460d9c996e737cad3f127a7ed1b7af9d168/package.json#L111

Had to revert back to 0.4.15.

**Comment by medikoo** [comment] 2024-05-24 08:13
Duplicate of #135

**Comment by medikoo** [comment] 2024-05-24 08:13
(also fixed and published with v0.4.17)

**Closed as completed by medikoo** 2024-05-24 08:13 UTC
Labels: duplicate
